exp_name: supervised_grid_search_toy
experiment: pydgn.experiment.supervised_task.SupervisedTask
higher_results_are_better: True
log_every: 1
dataset_getter: pydgn.data.provider.DataProvider
data_loader:
  class_name: torch_geometric.loader.DataLoader
  args:
    num_workers : 0  # > 0 only with --debug option and GPU device
    pin_memory: False  # True only with --debug option and GPU device
device: cpu
seed: 42
grid:
  supervised_config:
    model: pydgn.model.dgn.toy_dgn.ToyDGN
    checkpoint: True
    shuffle: True
    batch_size:
      - 32
    epochs:
      - 10
    dim_embedding:
      - 5
    num_layers:
      - 3
    aggregation:
      - mean
    optimizer:
      - class_name: pydgn.training.callback.optimizer.Optimizer
        args:
          optimizer_class_name: torch.optim.Adam
          lr: 0.01
          weight_decay: 0.
    scheduler:
      - null
    loss:
      - class_name: pydgn.training.callback.metric.AdditiveLoss
        args:
          loss1: pydgn.training.callback.metric.MulticlassClassification
          loss2: pydgn.training.callback.metric.MulticlassClassification
      - pydgn.training.callback.metric.MulticlassClassification
    scorer:
      - class_name: pydgn.training.callback.metric.MultiScore
        args:
          main_scorer: pydgn.training.callback.metric.MulticlassAccuracy
          my_metric2: pydgn.training.callback.metric.ToyMetric
    readout:
      - pydgn.model.readout.graph_readout.LinearGraphReadout
    engine:
      - pydgn.training.engine.TrainingEngine
    l2:
      - 0.
    gradient_clipper:
      - null
    dropout:
      - 0.
    early_stopper:
      - class_name:
          - pydgn.training.callback.early_stopping.PatienceEarlyStopper
        args:
          patience:
            - 3
          monitor: validation_main_score # (train_,validation_)[name_of_the_scorer_or_loss_to_monitor] -> we can use MAIN_LOSS or MAIN_SCORE
          mode: max
          checkpoint: True
    plotter:
      - pydgn.training.callback.plotter.Plotter
