model: model.dgn.toy_dgn.ToyDGN
experiment: experiment.semi_supervised_task.SemiSupervisedTask
higher_results_are_better: True
log_every: 1
dataset_getter: data.provider.DataProvider
device: cpu
num_dataloader_workers: 0  # > 0 only with --debug option and GPU device
pin_memory: False  # True only with --debug option and GPU device
grid:
  unsupervised_config:
    checkpoint: True
    batch_size:
      - 32
    epochs:
      - 10
    dim_embedding:
      - 5
    num_layers:
      - 3
    aggregation:
      - mean
    optimizer:
      - class_name: training.callback.optimizer.Optimizer
        args:
          optimizer_class_name: torch.optim.Adam
          lr: 0.01
          weight_decay: 0.
    scheduler:
      - null
    loss:
      - [ An unsupervised loss function ]
    scorer:
      - null
    predictor:
      - [ A predictor of your choice ]
    wrapper:
      - training.engine.TrainingEngine
    gradient_clipping:
      - null
    early_stopper:
      - null
    shuffle:
      - True
  supervised_config:
    checkpoint: True
    batch_size:
      - 32
    epochs:
      - 20
    dim_embedding:
      - 10
    num_layers:
      - 2
    aggregation:
      - mean
    optimizer:
      - class_name: training.callback.optimizer.Optimizer
        args:
          optimizer_class_name: torch.optim.Adam
          lr: 0.01
          weight_decay: 0.
    scheduler:
      - null
    loss:
      - training.callback.loss.MulticlassClassificationLoss
    scorer:
      - training.callback.score.MulticlassAccuracyScore
    predictor:
      - model.predictor.GraphPredictor.LinearGraphPredictor
    wrapper:
      - training.engine.TrainingEngine
    gradient_clipping:
      - null
    early_stopper:
      - class_name:
          - training.callback.early_stopping.PatienceEarlyStopper
        args:
          patience:
            - 5
          monitor: validation_Multiclass Accuracy # (train_,validation_)[name_of_the_scorer_or_loss_to_monitor]
          mode: max
          checkpoint: True
    plotter:
      - training.callback.plotter.Plotter
    shuffle:
      - True
