model: model.dgn.toy_dgn.ToyDGN
experiment: experiment.supervised_task.SupervisedTask
higher_results_are_better: True
log_every: 1
dataset_getter: data.provider.DataProvider
device: cuda
num_dataloader_workers: 3
pin_memory: True
num_samples: 3
seed: 42
random:
  supervised_config:
    checkpoint: True
    batch_size:
      sample_method: evaluation.util.choice
      args:
        - 32
        - 64
        - 128
    epochs: 10
    dim_embedding: 4
    num_layers:
      sample_method: evaluation.util.randint
      args:
        - 1  # min
        - 5  # max
    aggregation: mean
    optimizer:
      sample_method: evaluation.util.choice
      args:
        - class_name: training.callback.optimizer.Optimizer
          args:
            optimizer_class_name: torch.optim.Adam
            lr:
              sample_method: evaluation.util.normal
              args:
                - 0.001
                - 0.0001
            weight_decay: 0.
        - class_name: training.callback.optimizer.Optimizer
          args:
            optimizer_class_name: torch.optim.Adamax
            lr:
              sample_method: evaluation.util.loguniform
              args:
                - 0.0001
                - 0.01
            weight_decay: 0.
    scheduler: null
    loss: training.callback.loss.MulticlassClassificationLoss
    scorer:
      class_name: training.callback.score.MultiScore
      args:
        # used at model selection time. Should be the one on which to perform early stopping
        main_scorer: training.callback.score.MulticlassAccuracyScore
        my_metric2: training.callback.score.Toy1Score
    predictor: model.predictor.graph_predictor.LinearGraphPredictor
    wrapper: training.engine.TrainingEngine
    l2: 0.
    gradient_clipping: null
    dropout: 0.
    early_stopper:
      class_name: training.callback.early_stopping.PatienceEarlyStopper
      args:
        patience: 5
        # Should be the name of the main_scorer in MultiScore
        monitor: validation_Multiclass Accuracy # (train_,validation_)[name_of_the_scorer_or_loss_to_monitor]
        mode: max
        checkpoint: True
    plotter: training.callback.plotter.Plotter
    shuffle: True
