exp_name: semi_supervised_grid_search_toy
experiment: pydgn.experiment.semi_supervised_task.SemiSupervisedTask
higher_results_are_better: True
log_every: 1
dataset_getter: pydgn.data.provider.DataProvider
data_loader:
  class_name: torch_geometric.loader.DataLoader
  args:
    num_workers : 0  # > 0 only with --debug option and GPU device
    pin_memory: False  # True only with --debug option and GPU device
device: cpu
seed: 42
grid:
  unsupervised_config:  # unsupervised config to produce node/graph embeddings
    model: pydgn.model.dgn.toy_dgn.ToyDGN
    checkpoint: True
    batch_size:
      - 32
    epochs:
      - 10
    dim_embedding:
      - 5
    num_layers:
      - 3
    aggregation:
      - mean
    optimizer:
      - class_name: pydgn.training.callback.optimizer.Optimizer
        args:
          optimizer_class_name: torch.optim.Adam
          lr: 0.01
          weight_decay: 0.
    scheduler:
      - null
    loss:
      - [ An unsupervised loss function ]
    scorer:
      - null
    predictor:
      - pydgn.model.predictor.GraphPredictor.LinearGraphPredictor
    wrapper:
      - pydgn.training.engine.TrainingEngine
    gradient_clipping:
      - null
    early_stopper:
      - null
    shuffle:
      - True
  supervised_config:  # supervised config to classify/predict values associated with unsup. node/graph embeddings
    model: pydgn.model.dgn.toy_dgn.ToyDGN
    checkpoint: True
    batch_size:
      - 32
    epochs:
      - 20
    dim_embedding:
      - 10
    num_layers:
      - 2
    aggregation:
      - mean
    optimizer:
      - class_name: pydgn.training.callback.optimizer.Optimizer
        args:
          optimizer_class_name: torch.optim.Adam
          lr: 0.01
          weight_decay: 0.
    scheduler:
      - null
    loss:
      - pydgn.training.callback.metric.MulticlassClassification
    scorer:
      - pydgn.training.callback.metric.MulticlassAccuracy
    predictor:
      - null
    wrapper:
      - pydgn.training.engine.TrainingEngine
    gradient_clipping:
      - null
    early_stopper:
      - class_name:
          - pydgn.training.callback.early_stopping.PatienceEarlyStopper
        args:
          patience:
            - 5
          monitor: validation_Multiclass Accuracy # (train_,validation_)[name_of_the_scorer_or_loss_to_monitor]
          mode: max
          checkpoint: True
    plotter:
      - pydgn.training.callback.plotter.Plotter
    shuffle:
      - True
