model: toy_dgn_temporal.ToyDynamicDGN
experiment: pydgn.experiment.supervised_task.SupervisedTask
higher_results_are_better: False
log_every: 1
dataset_getter: dynamic_provider.SingleGraphSequenceDataProvider
device: cpu
num_dataloader_workers: 0  # > 0 only with --debug option and GPU device
pin_memory: False  # True only with --debug option and GPU device
seed: 42
grid:
  supervised_config:
    checkpoint: True
    batch_size:
      - 3
    epochs:
      - 100
    optimizer:
      - class_name: pydgn.training.callback.optimizer.Optimizer
        args:
          optimizer_class_name: torch.optim.Adam
          lr: 0.001
          weight_decay: 0.
    scheduler:
      - null
    loss:
      - pydgn.training.callback.loss.MeanSquareErrorLoss
      # class_name: pydgn.training.callback.loss.AdditiveLoss
      # args:
      #   loss1: pydgn.training.callback.loss.MulticlassClassificationLoss
      #   loss2: pydgn.training.callback.loss.MulticlassClassificationLoss
    scorer:
      - pydgn.training.callback.score.MeanSquareErrorScore
    predictor:
      - pydgn.model.predictor.node_predictor.LinearNodePredictor
    wrapper:
      - class_name: dynamic_engine.SingleGraphSequenceTrainingEngine
        args:
          engine_callback: dynamic_engine_callback.DynamicEngineCallback
    gradient_clipping:
      - null
    early_stopper:
      - class_name:
          - pydgn.training.callback.early_stopping.PatienceEarlyStopper
        args:
          patience:
            - 500
          # Should be the name of the main_scorer in MultiScore
          monitor: validation_MSE Score # (train_,validation_)[name_of_the_scorer_or_loss_to_monitor]
          mode: min
          checkpoint: True
    plotter:
      - pydgn.training.callback.plotter.Plotter
