# WARNING: This is just a debug configuration file
splitter:
  root: DATA_SPLITS/
  class_name: pydgn.data.temporal_splitter.TemporalSplitter
  args:
    n_outer_folds: 10
    n_inner_folds: 1
    seed: 42
    stratify: True  # works for graph classification tasks
    shuffle: True
    inner_val_ratio: 0.1
    outer_val_ratio: 0.1
    test_ratio: 0.1
dataset:
  root: DATA/
  class_name: pydgn.data.temporal_dataset.TUTemporalDatasetInterface
  args:
    root: DATA/
    name: infectious_ct1
