splitter:
  root: DATA_SPLITS/
  class_name: dynamic_splitter.SingleGraphSequenceSplitter
  args:
    # These are assumed to be 1 for a Single Graph Sequence
    # n_outer_folds: 1
    # n_inner_folds: 1
    seed: -1
    train_timesteps: 100
    valid_timesteps: 100
    test_timesteps: 100
dataset:
  root: DATA/
  class_name: dynamic_dataset.ChickenpoxDatasetInterface
  args:
    root: DATA/
    name: chickenpox
    lags: 1
