model: model.dgn.toy_dgn.ToyDGN
experiment: experiment.supervised_task.SupervisedTask
higher_results_are_better: True
log_every: 1
dataset-getter: data.provider.LinkPredictionSingleGraphDataProvider
device: cpu
num_dataloader_workers: 0  # > 0 only with --debug option and GPU device
pin_memory: False  # True only with --debug option and GPU device
grid:
  supervised_config:
    checkpoint: True
    batch_size:
      - 32
      # - 64
    epochs:
      - 10
    dim_embedding:
      - 4
    num_layers:
      - 5
    aggregation:
      - mean
    optimizer:
      -
        class_name: training.callback.optimizer.Optimizer
        args:
          optimizer_class_name: torch.optim.Adam
          lr: 0.01
          weight_decay: 0.

    scheduler:
      - null
    loss:
      # - training.callback.loss.MulticlassClassificationLoss
      - training.callback.loss.ToyLinkPredictionLoss
    scorer:
      #- training.callback.score.MulticlassAccuracyScore
      -
        class_name: training.callback.score.MultiScore
        args:
           # used at model selection time. Should be the one on which to perform early stopping
           #main_scorer: training.callback.score.MulticlassAccuracyScore
           #my_metric2: training.callback.score.Toy1Score
           main_scorer: training.callback.score.Toy1Score
    predictor:
      - model.predictor.node_predictor.LinearNodePredictor
    wrapper:
      - training.engine.TrainingEngine
    l2:
      - 0.
    gradient_clipping:
      - null
    dropout:
      - 0.
    early_stopper:
      -
        class_name:
          - training.callback.early_stopping.PatienceEarlyStopper
        args:
          patience:
            - 5
          # Should be the name of the main_scorer in MultiScore
          monitor: validation_Multiclass Accuracy # (train_,validation_)[name_of_the_scorer_or_loss_to_monitor]
          mode: max
          checkpoint: True
    plotter:
      - training.callback.plotter.Plotter
    shuffle:
      - True
