splitter:
  root: DATA_SPLITS/CHEMICAL
  class_name: pydgn.data.splitter.Splitter
  args:
    n_outer_folds: 5
    n_inner_folds: 3
    seed: 42
    stratify: True  # works for graph classification tasks
    shuffle: True
    inner_val_ratio: 0.1  # this will be ignored when the number of inner folds is > than 1
    outer_val_ratio: 0.1
    test_ratio: 0.1  # this will be ignored when the number of outer folds is > than 1
dataset:
  root: DATA/
  class_name: pydgn.data.dataset.TUDataset
  args:
    root: DATA/
    name: PROTEINS
  # useful for social datasets with no node features
  transform:
    - class_name: pydgn.data.transform.ConstantIfEmpty
      args:
        value: 1
